extract = 'total_dyn_inst: (\d+)'
benchmarks = 'benchmarks/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.tdce]
pipeline = [
    "bril2json",
    "_build/default/bin/main.exe tdce",
    "brili -p {args}",
]

[runs.dkp]
pipeline = [
    "bril2json",
    "_build/default/bin/main.exe dkp",
    "brili -p {args}",
]

[runs.tdce_plus]
pipeline = [
    "bril2json",
    "_build/default/bin/main.exe tdce+",
    "brili -p {args}",
]

[runs.lvn]
pipeline = [
    "bril2json",
    "_build/default/bin/main.exe lvn",
    "brili -p {args}",
]

[runs.full]
pipeline = [
    "bril2json",
    "_build/default/bin/main.exe full",
    "brili -p {args}",
]
