extract = 'total_dyn_inst: (\d+)'
benchmarks = './benchmarks/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.myopt]
pipeline = [
    "bril2json",
    "dune exec -- main",
    "brili -p {args}",
]
